import { Product } from '@/types';

export const SEED_PRODUCTS: Product[] = [
  // HOT Products (High demand tech & flagship items)
  {
    id: 'prod-001',
    name: 'iPhone 17 Pro Max 256GB Titanium',
    category: 'Smartphones',
    price: 1199,
    description: 'Next-generation smartphone with A19 Pro Bionic, ProMotion 120Hz display, and periscope zoom.',
    rating: 4.9,
    reviewCount: 3420,
    stock: 145,
    sku: 'AAPL-IP17-TI',
    tags: ['flagship', 'apple', 'smartphone', 'hot'],
    baseDemand: 'HOT',
  },
  {
    id: 'prod-002',
    name: 'MacBook Pro 16" M4 Max 64GB Unified',
    category: 'Laptops',
    price: 3499,
    description: 'Extreme computing power with 40-core GPU, Liquid Retina XDR, and 22-hour battery life.',
    rating: 4.9,
    reviewCount: 1890,
    stock: 58,
    sku: 'AAPL-MBP16-M4',
    tags: ['workstation', 'creator', 'laptop', 'hot'],
    baseDemand: 'HOT',
  },
  {
    id: 'prod-003',
    name: 'Sony WH-1000XM6 Wireless Noise Cancelling Headphones',
    category: 'Audio',
    price: 399,
    description: 'Industry-leading active noise cancellation with dual processors, LDAC codec, and 30h battery.',
    rating: 4.8,
    reviewCount: 4510,
    stock: 210,
    sku: 'SNY-WH1000XM6',
    tags: ['audio', 'anc', 'wireless', 'hot'],
    baseDemand: 'HOT',
  },
  {
    id: 'prod-004',
    name: 'Samsung Galaxy S25 Ultra 512GB AI Edition',
    category: 'Smartphones',
    price: 1299,
    description: 'Dynamic AMOLED 2X with built-in S-Pen, 200MP camera sensor, and Galaxy AI live features.',
    rating: 4.8,
    reviewCount: 2780,
    stock: 92,
    sku: 'SMSNG-S25U-BLK',
    tags: ['samsung', 'android', 'flagship', 'hot'],
    baseDemand: 'HOT',
  },
  {
    id: 'prod-005',
    name: 'NVIDIA GeForce RTX 5090 32GB GDDR7',
    category: 'Gaming',
    price: 1999,
    description: 'Ultra-enthusiast Blackwell graphics card with DLSS 4 frame generation and 8K ray tracing.',
    rating: 4.9,
    reviewCount: 920,
    stock: 18,
    sku: 'NVDA-RTX5090',
    tags: ['gpu', 'gaming', 'pc-hardware', 'hot'],
    baseDemand: 'HOT',
  },
  {
    id: 'prod-006',
    name: 'Apple Watch Ultra 3 Titanium GPS+Cellular',
    category: 'Wearables',
    price: 799,
    description: 'Rugged dive and endurance smartwatch with 3000-nit micro-OLED display and dual-frequency GPS.',
    rating: 4.7,
    reviewCount: 1640,
    stock: 84,
    sku: 'AAPL-AWU3-TI',
    tags: ['smartwatch', 'fitness', 'rugged', 'hot'],
    baseDemand: 'HOT',
  },
  {
    id: 'prod-007',
    name: 'Dell XPS 15 OLED Touch Intel Core Ultra 9',
    category: 'Laptops',
    price: 2299,
    description: 'Precision CNC aluminum chassis with 3.5K OLED InfinityEdge touchscreen and RTX 4070.',
    rating: 4.6,
    reviewCount: 880,
    stock: 45,
    sku: 'DELL-XPS15-OLED',
    tags: ['laptop', 'ultrabook', 'windows', 'hot'],
    baseDemand: 'HOT',
  },

  // WARM Products (Regular popular items)
  {
    id: 'prod-008',
    name: 'Logitech MX Master 3S Wireless Performance Mouse',
    category: 'Accessories',
    price: 99,
    description: 'Quiet-click ergonomic mouse with 8000 DPI Darkfield sensor and MagSpeed magnetic scroll.',
    rating: 4.9,
    reviewCount: 6120,
    stock: 320,
    sku: 'LOGI-MXM3S-GRY',
    tags: ['mouse', 'productivity', 'wireless', 'warm'],
    baseDemand: 'WARM',
  },
  {
    id: 'prod-009',
    name: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
    category: 'Accessories',
    price: 199,
    description: '75% aluminum gasket-mount keyboard with hot-swappable switches and QMK/VIA programmability.',
    rating: 4.8,
    reviewCount: 1450,
    stock: 110,
    sku: 'KCHRN-Q1PRO-RD',
    tags: ['keyboard', 'mechanical', 'custom', 'warm'],
    baseDemand: 'WARM',
  },
  {
    id: 'prod-010',
    name: 'LG UltraGear 34" Curved OLED Gaming Monitor',
    category: 'Gaming',
    price: 999,
    description: '240Hz 0.03ms response time ultrawide OLED with HDR True Black 400 and G-Sync compatibility.',
    rating: 4.7,
    reviewCount: 760,
    stock: 35,
    sku: 'LG-34GS95QE',
    tags: ['monitor', 'oled', 'gaming', 'warm'],
    baseDemand: 'WARM',
  },
  {
    id: 'prod-011',
    name: 'Bose QuietComfort Ultra Earbuds',
    category: 'Audio',
    price: 299,
    description: 'Breakthrough spatial audio with CustomTune sound calibration and world-class noise cancellation.',
    rating: 4.6,
    reviewCount: 2310,
    stock: 180,
    sku: 'BOSE-QCU-EAR',
    tags: ['audio', 'earbuds', 'anc', 'warm'],
    baseDemand: 'WARM',
  },
  {
    id: 'prod-012',
    name: 'Sony PlayStation 5 Pro 2TB Console',
    category: 'Gaming',
    price: 699,
    description: 'Advanced ray tracing console with PlayStation Spectral Super Resolution (PSSR) AI upscaling.',
    rating: 4.8,
    reviewCount: 3100,
    stock: 75,
    sku: 'SNY-PS5PRO-2TB',
    tags: ['gaming', 'console', 'playstation', 'warm'],
    baseDemand: 'WARM',
  },
  {
    id: 'prod-013',
    name: 'Kindle Paperwhite Signature Edition 32GB',
    category: 'Electronics',
    price: 189,
    description: '6.8" 300 ppi glare-free display with auto-adjusting warm front light and wireless charging.',
    rating: 4.8,
    reviewCount: 5200,
    stock: 240,
    sku: 'AMZN-KPW-SIG',
    tags: ['ereader', 'kindle', 'books', 'warm'],
    baseDemand: 'WARM',
  },
  {
    id: 'prod-014',
    name: 'Anker Prime 27,650mAh Power Bank 250W',
    category: 'Accessories',
    price: 179,
    description: 'Multi-device fast charging power bank with digital smart display and Bluetooth app tracking.',
    rating: 4.7,
    reviewCount: 1980,
    stock: 165,
    sku: 'ANKR-PRIME-250',
    tags: ['charging', 'powerbank', 'usb-c', 'warm'],
    baseDemand: 'WARM',
  },
  {
    id: 'prod-015',
    name: 'DJI Mini 4 Pro Fly More Combo Plus',
    category: 'Cameras',
    price: 1099,
    description: 'Sub-249g foldable drone with omnidirectional obstacle sensing and 4K/60fps HDR true vertical video.',
    rating: 4.9,
    reviewCount: 1120,
    stock: 42,
    sku: 'DJI-MINI4P-FMC',
    tags: ['drone', 'camera', 'dji', 'warm'],
    baseDemand: 'WARM',
  },

  // COLD / NICHE Products (Rarely visited or legacy items - ideal eviction & viral surge candidates!)
  {
    id: 'prod-016',
    name: 'Vintage Model M Clicky Buckling Spring Keyboard',
    category: 'Accessories',
    price: 129,
    description: 'Classic heavy-duty mechanical typing keyboard with authentic tactile buckling spring click feel.',
    rating: 4.5,
    reviewCount: 88,
    stock: 15,
    sku: 'VNTG-MOD-M-1989',
    tags: ['retro', 'vintage', 'keyboard', 'cold'],
    baseDemand: 'COLD',
  },
  {
    id: 'prod-017',
    name: 'Legacy 30-Pin to Lightning Dock Adapter',
    category: 'Accessories',
    price: 19,
    description: 'Original legacy audio and charging adapter for older generation media docks and speakers.',
    rating: 3.9,
    reviewCount: 42,
    stock: 90,
    sku: 'LGCY-30PIN-LGT',
    tags: ['legacy', 'adapter', 'cable', 'cold'],
    baseDemand: 'COLD',
  },
  {
    id: 'prod-018',
    name: 'Parallel Port to USB Bi-Directional Converter',
    category: 'Accessories',
    price: 24,
    description: 'IEEE 1284 DB25 parallel printer cable for retro matrix dot and industrial legacy printers.',
    rating: 4.1,
    reviewCount: 19,
    stock: 35,
    sku: 'PRL-USB-DB25',
    tags: ['industrial', 'legacy', 'cable', 'cold'],
    baseDemand: 'COLD',
  },
  {
    id: 'prod-019',
    name: 'MiniDisc Rewritable 80-Minute Audio Pack (5-Pack)',
    category: 'Audio',
    price: 49,
    description: 'High-grade magneto-optical ATRAC discs for vintage portable and deck MiniDisc players.',
    rating: 4.7,
    reviewCount: 28,
    stock: 22,
    sku: 'SNY-MD80-5PK',
    tags: ['retro', 'minidisc', 'audio', 'cold'],
    baseDemand: 'COLD',
  },
  {
    id: 'prod-020',
    name: 'VGA to RCA Composite Video Scan Converter',
    category: 'Electronics',
    price: 29,
    description: 'Analog standard definition downscaler box with NTSC/PAL switch for CRT monitors.',
    rating: 3.7,
    reviewCount: 31,
    stock: 60,
    sku: 'VGA-RCA-BOX',
    tags: ['analog', 'converter', 'video', 'cold'],
    baseDemand: 'COLD',
  },
  {
    id: 'prod-021',
    name: 'PS/2 Dual Mouse & Keyboard Splitter Cable',
    category: 'Accessories',
    price: 12,
    description: '6-Pin mini DIN Y-cable splitter for legacy server racks and KVM switches.',
    rating: 4.2,
    reviewCount: 15,
    stock: 80,
    sku: 'PS2-SPLIT-6PIN',
    tags: ['server', 'kvm', 'legacy', 'cold'],
    baseDemand: 'COLD',
  },
  {
    id: 'prod-022',
    name: 'Floppy Disk USB 3.5" External Reader Drive',
    category: 'Electronics',
    price: 34,
    description: 'Plug-and-play 1.44MB FDD drive for reading archive data on Windows and Mac.',
    rating: 4.3,
    reviewCount: 54,
    stock: 40,
    sku: 'USB-FDD-144',
    tags: ['retro', 'floppy', 'storage', 'cold'],
    baseDemand: 'COLD',
  },
  {
    id: 'prod-023',
    name: 'SCSI-2 50-Pin Centronics Terminator Plug',
    category: 'Accessories',
    price: 18,
    description: 'Active SCSI differential termination block for classic server workstations.',
    rating: 4.4,
    reviewCount: 12,
    stock: 25,
    sku: 'SCSI-TERM-50P',
    tags: ['scsi', 'server', 'vintage', 'cold'],
    baseDemand: 'COLD',
  },
  {
    id: 'prod-024',
    name: 'Handheld Cassette Voice Dictaphone with Micro-Tape',
    category: 'Audio',
    price: 65,
    description: 'Dual-speed analog voice recorder with cue/review and built-in dynamic condenser mic.',
    rating: 4.0,
    reviewCount: 22,
    stock: 18,
    sku: 'ANLG-DICT-TAPE',
    tags: ['audio', 'analog', 'dictaphone', 'cold'],
    baseDemand: 'COLD',
  },

  // Additional Expanded Catalog (More variety for stress testing & rich catalog)
  {
    id: 'prod-025',
    name: 'Fujifilm X100VI Digital Camera Silver',
    category: 'Cameras',
    price: 1599,
    description: '40.2MP X-Trans CMOS 5 HR sensor with in-body image stabilization and film simulations.',
    rating: 4.9,
    reviewCount: 890,
    stock: 12,
    sku: 'FUJI-X100VI-SLV',
    tags: ['camera', 'street-photography', 'hot'],
    baseDemand: 'HOT',
  },
  {
    id: 'prod-026',
    name: 'ASUS ROG Ally X Handheld Gaming PC 1TB',
    category: 'Gaming',
    price: 799,
    description: 'AMD Ryzen Z1 Extreme, 24GB LPDDR5X RAM, 80Wh battery, and 120Hz FHD VRR display.',
    rating: 4.7,
    reviewCount: 1420,
    stock: 65,
    sku: 'ASUS-ROG-ALLYX',
    tags: ['gaming', 'handheld', 'pc', 'warm'],
    baseDemand: 'WARM',
  },
  {
    id: 'prod-027',
    name: 'Elgato Stream Deck MK.2 15 LCD Keys',
    category: 'Accessories',
    price: 149,
    description: 'Customizable tactile LCD keys for broadcast control, studio automations, and macro triggers.',
    rating: 4.8,
    reviewCount: 3890,
    stock: 140,
    sku: 'ELG-STRMDECK-MK2',
    tags: ['streaming', 'creator', 'productivity', 'warm'],
    baseDemand: 'WARM',
  },
  {
    id: 'prod-028',
    name: 'Sonos Move 2 Portable Smart Speaker',
    category: 'Audio',
    price: 449,
    description: 'Stereo sound portable speaker with Wi-Fi, Bluetooth, AirPlay 2, and 24h battery life.',
    rating: 4.6,
    reviewCount: 940,
    stock: 55,
    sku: 'SNS-MOVE2-BLK',
    tags: ['audio', 'smart-home', 'portable', 'warm'],
    baseDemand: 'WARM',
  },
  {
    id: 'prod-029',
    name: 'Shure SM7B Cardioid Dynamic Vocal Microphone',
    category: 'Audio',
    price: 399,
    description: 'Legendary broadcast voice microphone with flat, wide-range frequency response for studio speech.',
    rating: 4.9,
    reviewCount: 4120,
    stock: 85,
    sku: 'SHR-SM7B-MIC',
    tags: ['audio', 'podcast', 'studio', 'warm'],
    baseDemand: 'WARM',
  },
  {
    id: 'prod-030',
    name: 'CalDigit TS4 Thunderbolt 4 Dock 18 Ports',
    category: 'Accessories',
    price: 399,
    description: 'Single-cable dock with 98W charging, dual 6K display support, and 2.5GbE ethernet.',
    rating: 4.7,
    reviewCount: 1100,
    stock: 48,
    sku: 'CALD-TS4-TB4',
    tags: ['dock', 'thunderbolt', 'accessories', 'warm'],
    baseDemand: 'WARM',
  },
];
